[package]
name = "transform"
version = "0.1.0"
edition = "2024"

[dependencies]
processor_engine = {path = "../processor_engine"}
stream_proc_macro = {path = "../processor_engine/src/stream_proc_macro"}
num-traits = "0.2.19"
