[package]
name = "kappa_library"
version = "0.1.0"
edition = "2021"

[dependencies]
connectors_macro = {path = "src/connectors_macro"}
stream_proc_macro = {path = "src/stream_proc_macro"}
num-traits = "0.2.19"
libloading = "0.9.0"
