[package]
name = "data_model"
version = "0.1.0"
edition = "2024"

[dependencies]
memory_var_macro = { path = "src/memory_var_macro"}
libloading = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
